# Generated by Django 3.0.7 on 2020-08-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Bloggy post', max_length=50),
        ),
    ]
